version: 0.2

phases:
  install:
    commands:
      - npm install
      - rm -rf node_modules/sharp
      - npm install --arch=x64 --platform=linux --target=10.15.0 sharp
      - rm -rf node_modules/exiftool.js/test
  build:
    commands:
      - rm -rf test_files
      - chmod -R +x bin
      - npx serverless deploy
