version: 0.2

phases:
  install:
    commands:
      - npm install
  post_build:
    commands:
      - rm -rf test_files
      - npm install -g serverless
      - chmod -R +x bin
      - serverless deploy
