# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: TBA21-helpers # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - Ref: TBA21FileProcessorStateMachine
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::acrossthecloud-tba21-helper-test/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/tba21*"

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions

functions:
  master:
    handler: master.start
    events:
      - s3: acrossthecloud-tba21-helper-test
    environment:
      stateMachineArn: ${self:resources.Outputs.TBA21FileProcessorStateMachine.Value}
  generateMP3:
    handler: generate_mp3.handler
  image_tagger:
    handler: image_tagger.handler
    environment:
      IMAGE_TAG_TABLE: tba21-image-tags-dev
  example:
    handler: example.handler

stepFunctions:
  stateMachines:
    hellostepfunc:
      name: TBA21FileProcessorStateMachine
      definition:
        StartAt: Parallel
        States:
          Parallel:
            Type: Parallel
            Next: Final State
            Branches:
            - StartAt: generateMP3
              States:
                generateMP3:
                  Type: Task
                  Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-generateMP3
                  End: true
            - StartAt: example
              States:
                example:
                  Type: Task
                  Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-example
                  End: true
          Final State:
            Type: Pass
            End: true

resources:
  Outputs:
    TBA21FileProcessorStateMachine:
      Description: The ARN of the example state machine
      Value:
        Ref: TBA21FileProcessorStateMachine
